const URL = 'https://github.com/';
const USER = 'Vincenzofdg';
const MASTER = 'archive/refs/heads/master.zip';

const data = [
  {
    id: 1,
    name: 'Pixels Art',
    gif: true,
    internet: `https://${USER}.github.io/Pixels-Art`,
    repositorie: `${URL}${USER}/Pixels-Art`,
    downloadLink: `${URL}${USER}/Pixels-Art/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 2,
    name: 'To Do List',
    gif: true,
    internet: `https://${USER}.github.io/To-Do-List`,
    repositorie: `${URL}${USER}/To-Do-List`,
    downloadLink: `${URL}${USER}/To-Do-List/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 3,
    name: 'Mistery Letter',
    gif: true,
    internet: `https://${USER}.github.io/Mistery-Letter`,
    repositorie: `${URL}${USER}/Mistery-Letter`,
    downloadLink: `${URL}${USER}/Mistery-Letter/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 4,
    name: 'Hogwarts Application',
    gif: true,
    internet: `https://${USER}.github.io/Hogwarts-Application`,
    repositorie: `${URL}${USER}/Hogwarts-Application`,
    downloadLink: `${URL}${USER}/Hogwarts-Application/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 5,
    name: 'Shopping Cart',
    gif: true,
    internet: `https://${USER}.github.io/Shopping-Cart`,
    repositorie: `${URL}${USER}/Shopping-Cart`,
    downloadLink: `${URL}${USER}/Shopping-Cart/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 6,
    name: 'Shopping Shirt',
    gif: true,
    internet: `https://${USER}.github.io/Shopping-Shirt`,
    repositorie: `${URL}${USER}/Shopping-Shirt`,
    downloadLink: `${URL}${USER}/Shopping-Shirt/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 7,
    name: 'Naruto Movies',
    gif: true,
    internet: `https://${USER}.github.io/Naruto-Movies`,
    repositorie: `${URL}${USER}/Naruto-Movies`,
    downloadLink: `${URL}${USER}/Naruto-Movies/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 8,
    name: 'Movie Library',
    gif: true,
    internet: `https://${USER}.github.io/Movie-Library`,
    repositorie: `${URL}${USER}/Movie-Library`,
    downloadLink: `${URL}${USER}/Movie-Library/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 9,
    name: 'TypeScript Data Base',
    image: 'TypeScript',
    gif: false,
    repositorie: `${URL}${USER}/TypeScript_DataBase`,
    downloadLink: `${URL}${USER}/TypeScript_DataBase/${MASTER}`,
    type: ['All', 'TypeScript'],
  },
  {
    id: 10,
    name: 'Flappy Bird',
    gif: true,
    internet: `https://${USER}.github.io/Flappy-Bird`,
    repositorie: `${URL}${USER}/Flappy-Bird`,
    downloadLink: `${URL}${USER}/Flappy-Bird/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 11,
    name: 'MyTunes',
    gif: true,
    internet: `https://${USER}.github.io/MyTunes`,
    repositorie: `${URL}${USER}/MyTunes`,
    downloadLink: `${URL}${USER}/MyTunes/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
  {
    id: 12,
    name: 'Trybe (2021-2022)',
    image: 'Trybe',
    gif: false,
    repositorie: `${URL}${USER}/Study_-_Full_Stack`,
    downloadLink: `${URL}${USER}/Study_-_Full_Stack/${MASTER}`,
    type: ['Study'],
  },
  {
    id: 13,
    name: 'Java Wipro (2022)',
    image: 'Wipro',
    gif: false,
    repositorie: `${URL}${USER}/Study_-_Java`,
    downloadLink: `${URL}${USER}/Study_-_Java/${MASTER}`,
    type: ['Study'],
  },
  {
    id: 14,
    name: 'Software Enginnering',
    image: 'Anhanguera',
    gif: false,
    repositorie: `${URL}${USER}/Study_-_Software_Enginnering`,
    downloadLink: `${URL}${USER}/Study_-_Software_Enginnering/${MASTER}`,
    type: ['Study'],
  },
  {
    id: 15,
    name: 'C sharp',
    image: 'C sharp',
    gif: false,
    repositorie: `${URL}${USER}/Study_-_Csharp`,
    downloadLink: `${URL}${USER}/Study_-_Csharp/${MASTER}`,
    type: ['Study'],
  },
  {
    id: 16,
    name: 'Shell Script',
    image: 'Shell Script',
    gif: false,
    repositorie: `${URL}${USER}/Study_-_Shell_Script`,
    downloadLink: `${URL}${USER}/Study_-_Shell_Script/${MASTER}`,
    type: ['Study'],
  },
  {
    id: 17,
    name: 'Menu Recipes',
    gif: true,
    internet: `https://${USER}.github.io/Menu-Recipes`,
    repositorie: `${URL}${USER}/Menu-Recipes`,
    downloadLink: `${URL}${USER}/Menu-Recipes/${MASTER}`,
    type: ['All', 'JavaScript'],
  },
]

export default data;
